baseURL = ""
# title = "Hugo Themes"
author = ""
copyright = "Copyright © 2008–2023, "
paginate = 6
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# 
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "paper"
title = "DVart"

[params]
  color = 'wheat'

  # twitter = ''
  facebook = 'DVArtnz'
  instagram = 'dva_art_nz/'

  avatar = ''
  name = 'DVart'
  bio = 'Sharing the wonder of the natural world one image at a time.'
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
 
    
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

[[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 20

 [[menu.main]]
    identifier = "post"
    name = "Blog"
    url = "/post/"
    weight = 30

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

 [privacy.facebook]
    disabled = false
    simple = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[services.facebook]
    disableInlineCSS = true
